# Crafting Theme - Advanced Crafting System Tests
# Advanced crafting features including UI, automation, economy, and analytics

# Phase 8: User Interface Integration
# test_crafting_phase8_ui - Crafting UI system and player interactions
add_executable(test_crafting_phase8_ui tests/unit/test_crafting_phase8_ui.c)
target_link_libraries(test_crafting_phase8_ui rogue_core)
if(TARGET SDL2::SDL2)
    target_link_libraries(test_crafting_phase8_ui SDL2::SDL2)
    target_compile_definitions(test_crafting_phase8_ui PRIVATE ROGUE_HAVE_SDL=1)
endif()

# Phase 9: Automation Systems
# test_crafting_phase9_automation - Crafting automation and batch processing
add_executable(test_crafting_phase9_automation tests/unit/test_crafting_phase9_automation.c)
target_link_libraries(test_crafting_phase9_automation rogue_core)
if(TARGET SDL2::SDL2)
    target_link_libraries(test_crafting_phase9_automation SDL2::SDL2)
    target_compile_definitions(test_crafting_phase9_automation PRIVATE ROGUE_HAVE_SDL=1)
endif()

# Phase 10: Economic Integration
# test_crafting_phase10_economy - Economic impact and resource flow in crafting
add_executable(test_crafting_phase10_economy tests/unit/test_crafting_phase10_economy.c)
target_link_libraries(test_crafting_phase10_economy rogue_core)
if(TARGET SDL2::SDL2)
    target_link_libraries(test_crafting_phase10_economy SDL2::SDL2)
    target_compile_definitions(test_crafting_phase10_economy PRIVATE ROGUE_HAVE_SDL=1)
endif()

# Phase 11: Analytics and Metrics
# test_crafting_phase11_analytics - Crafting analytics, statistics, and performance metrics
add_executable(test_crafting_phase11_analytics tests/unit/test_crafting_phase11_analytics.c)
target_link_libraries(test_crafting_phase11_analytics rogue_core)
if(TARGET SDL2::SDL2)
    target_link_libraries(test_crafting_phase11_analytics SDL2::SDL2)
    target_compile_definitions(test_crafting_phase11_analytics PRIVATE ROGUE_HAVE_SDL=1)
endif()

# Phase 5 crafting skill test explicit add (ensure included regardless of glob ordering)
if(EXISTS ${CMAKE_CURRENT_LIST_DIR}/unit/test_crafting_phase5_skill.c)
    add_executable(test_crafting_phase5_skill unit/test_crafting_phase5_skill.c)
    target_link_libraries(test_crafting_phase5_skill PRIVATE rogue_core)
    add_test(NAME test_crafting_phase5_skill COMMAND test_crafting_phase5_skill)
endif()

# Phase 6 enhancement pathways test
if(EXISTS ${CMAKE_CURRENT_LIST_DIR}/unit/test_crafting_phase6_enhancement.c)
    add_executable(test_crafting_phase6_enhancement unit/test_crafting_phase6_enhancement.c)
    target_link_libraries(test_crafting_phase6_enhancement PRIVATE rogue_core)
    add_test(NAME test_crafting_phase6_enhancement COMMAND test_crafting_phase6_enhancement)
endif()
if(EXISTS ${CMAKE_CURRENT_LIST_DIR}/unit/test_crafting_phase6_3_transmute_scaling.c)
    add_executable(test_crafting_phase6_3_transmute_scaling unit/test_crafting_phase6_3_transmute_scaling.c)
    target_link_libraries(test_crafting_phase6_3_transmute_scaling PRIVATE rogue_core)
    add_test(NAME test_crafting_phase6_3_transmute_scaling COMMAND test_crafting_phase6_3_transmute_scaling)
endif()
if(EXISTS ${CMAKE_CURRENT_LIST_DIR}/unit/test_crafting_phase7_rng_journal.c)
    add_executable(test_crafting_phase7_rng_journal unit/test_crafting_phase7_rng_journal.c)
    target_link_libraries(test_crafting_phase7_rng_journal PRIVATE rogue_core)
    add_test(NAME test_crafting_phase7_rng_journal COMMAND test_crafting_phase7_rng_journal)
endif()
if(EXISTS ${CMAKE_CURRENT_LIST_DIR}/unit/test_crafting_phase7_determinism.c)
    add_executable(test_crafting_phase7_determinism unit/test_crafting_phase7_determinism.c)
    target_link_libraries(test_crafting_phase7_determinism PRIVATE rogue_core)
    add_test(NAME test_crafting_phase7_determinism COMMAND test_crafting_phase7_determinism)
endif()

# Crafting & Gathering Phase 0-1 material registry test
if(EXISTS ${CMAKE_CURRENT_SOURCE_DIR}/unit/test_crafting_phase0_1_material_registry.c AND NOT TARGET test_crafting_phase0_1_material_registry)
    add_executable(test_crafting_phase0_1_material_registry unit/test_crafting_phase0_1_material_registry.c)
    target_link_libraries(test_crafting_phase0_1_material_registry PRIVATE rogue_core)
    if(TARGET SDL2::SDL2main)
        target_link_libraries(test_crafting_phase0_1_material_registry PRIVATE SDL2::SDL2main SDL2::SDL2)
        target_compile_definitions(test_crafting_phase0_1_material_registry PRIVATE ROGUE_HAVE_SDL=1)
    endif()
    add_test(NAME test_crafting_phase0_1_material_registry COMMAND test_crafting_phase0_1_material_registry)
endif()

# Crafting & Gathering Phase 2 gathering nodes test
if(EXISTS ${CMAKE_CURRENT_SOURCE_DIR}/unit/test_crafting_phase2_gathering.c AND NOT TARGET test_crafting_phase2_gathering)
    add_executable(test_crafting_phase2_gathering unit/test_crafting_phase2_gathering.c)
    target_link_libraries(test_crafting_phase2_gathering PRIVATE rogue_core)
    if(TARGET SDL2::SDL2main)
        target_link_libraries(test_crafting_phase2_gathering PRIVATE SDL2::SDL2main SDL2::SDL2)
        target_compile_definitions(test_crafting_phase2_gathering PRIVATE ROGUE_HAVE_SDL=1)
    endif()
    add_test(NAME test_crafting_phase2_gathering COMMAND test_crafting_phase2_gathering)
endif()

# Crafting & Gathering Phase 3 refinement test
if(EXISTS ${CMAKE_CURRENT_SOURCE_DIR}/unit/test_crafting_phase3_refinement.c AND NOT TARGET test_crafting_phase3_refinement)
    add_executable(test_crafting_phase3_refinement unit/test_crafting_phase3_refinement.c)
    target_link_libraries(test_crafting_phase3_refinement PRIVATE rogue_core)
    if(TARGET SDL2::SDL2main)
        target_link_libraries(test_crafting_phase3_refinement PRIVATE SDL2::SDL2main SDL2::SDL2)
        target_compile_definitions(test_crafting_phase3_refinement PRIVATE ROGUE_HAVE_SDL=1)
    endif()
    add_test(NAME test_crafting_phase3_refinement COMMAND test_crafting_phase3_refinement)
endif()
 # Crafting & Gathering Phase 4 recipe parsing test
if(EXISTS ${CMAKE_CURRENT_SOURCE_DIR}/unit/test_crafting_phase4_recipes.c AND NOT TARGET test_crafting_phase4_recipes)
    add_executable(test_crafting_phase4_recipes unit/test_crafting_phase4_recipes.c)
    target_link_libraries(test_crafting_phase4_recipes PRIVATE rogue_core)
    if(TARGET SDL2::SDL2main)
        target_link_libraries(test_crafting_phase4_recipes PRIVATE SDL2::SDL2main SDL2::SDL2)
        target_compile_definitions(test_crafting_phase4_recipes PRIVATE ROGUE_HAVE_SDL=1)
    endif()
    add_test(NAME test_crafting_phase4_recipes COMMAND test_crafting_phase4_recipes)
endif()
 # Crafting & Gathering Phase 4 queue & stations test
if(EXISTS ${CMAKE_CURRENT_SOURCE_DIR}/unit/test_crafting_phase4_queue.c AND NOT TARGET test_crafting_phase4_queue)
    add_executable(test_crafting_phase4_queue unit/test_crafting_phase4_queue.c)
    target_link_libraries(test_crafting_phase4_queue PRIVATE rogue_core)
    if(TARGET SDL2::SDL2main)
        target_link_libraries(test_crafting_phase4_queue PRIVATE SDL2::SDL2main SDL2::SDL2)
        target_compile_definitions(test_crafting_phase4_queue PRIVATE ROGUE_HAVE_SDL=1)
    endif()
    add_test(NAME test_crafting_phase4_queue COMMAND test_crafting_phase4_queue)
endif()

# Crafting system tests (11.2 - 11.6)
if(EXISTS ${CMAKE_CURRENT_SOURCE_DIR}/unit/test_crafting_basic.c AND NOT TARGET test_crafting_basic)
    add_executable(test_crafting_basic unit/test_crafting_basic.c)
    target_link_libraries(test_crafting_basic PRIVATE rogue_core)
    if(ROGUE_ENABLE_SDL)
        target_compile_definitions(test_crafting_basic PRIVATE ROGUE_HAVE_SDL=1)
    endif()
    add_test(NAME test_crafting_basic COMMAND test_crafting_basic)
endif()

# Integration Plumbing Phase 2.3.3 Materials & Crafting JSON tests
if(EXISTS ${CMAKE_CURRENT_LIST_DIR}/unit/test_materials_and_gathering_json.c AND NOT TARGET test_materials_and_gathering_json)
    add_executable(test_materials_and_gathering_json unit/test_materials_and_gathering_json.c)
    target_link_libraries(test_materials_and_gathering_json PRIVATE rogue_core)
    if(TARGET SDL2::SDL2)
        target_link_libraries(test_materials_and_gathering_json PRIVATE SDL2::SDL2)
        target_compile_definitions(test_materials_and_gathering_json PRIVATE ROGUE_HAVE_SDL=1)
    endif()
    add_test(NAME test_materials_and_gathering_json COMMAND test_materials_and_gathering_json)
endif()

if(EXISTS ${CMAKE_CURRENT_LIST_DIR}/unit/test_crafting_json_and_validations.c AND NOT TARGET test_crafting_json_and_validations)
    add_executable(test_crafting_json_and_validations unit/test_crafting_json_and_validations.c)
    target_link_libraries(test_crafting_json_and_validations PRIVATE rogue_core)
    if(TARGET SDL2::SDL2)
        target_link_libraries(test_crafting_json_and_validations PRIVATE SDL2::SDL2)
        target_compile_definitions(test_crafting_json_and_validations PRIVATE ROGUE_HAVE_SDL=1)
    endif()
    add_test(NAME test_crafting_json_and_validations COMMAND test_crafting_json_and_validations)
endif()
