# Talents-related unit tests

# Talents Phase 1B open allocation + cost-aware unlocks
if(EXISTS ${CMAKE_CURRENT_SOURCE_DIR}/unit/test_talents_phase1b_open_allocation.c AND NOT TARGET test_talents_phase1b_open_allocation)
    add_executable(test_talents_phase1b_open_allocation unit/test_talents_phase1b_open_allocation.c)
    target_link_libraries(test_talents_phase1b_open_allocation PRIVATE rogue_core)
    target_compile_definitions(test_talents_phase1b_open_allocation PRIVATE SDL_MAIN_HANDLED=1)
    if(ROGUE_ENABLE_SDL)
        target_compile_definitions(test_talents_phase1b_open_allocation PRIVATE ROGUE_HAVE_SDL=1)
    endif()
    add_test(NAME test_talents_phase1b_open_allocation COMMAND test_talents_phase1b_open_allocation)
endif()

if(EXISTS ${CMAKE_CURRENT_SOURCE_DIR}/unit/test_talents_phase1b_dag_and_modifiers.c AND NOT TARGET test_talents_phase1b_dag_and_modifiers)
    add_executable(test_talents_phase1b_dag_and_modifiers unit/test_talents_phase1b_dag_and_modifiers.c)
    target_link_libraries(test_talents_phase1b_dag_and_modifiers PRIVATE rogue_core)
    if(TARGET SDL2::SDL2)
        target_link_libraries(test_talents_phase1b_dag_and_modifiers PRIVATE SDL2::SDL2)
        target_compile_definitions(test_talents_phase1b_dag_and_modifiers PRIVATE ROGUE_HAVE_SDL=1 SDL_MAIN_HANDLED=1)
    else()
        target_compile_definitions(test_talents_phase1b_dag_and_modifiers PRIVATE SDL_MAIN_HANDLED=1)
    endif()
    add_test(NAME test_talents_phase1b_dag_and_modifiers COMMAND test_talents_phase1b_dag_and_modifiers)
endif()

# Talents Phase 1B ranks + hash stability test
if(EXISTS ${CMAKE_CURRENT_SOURCE_DIR}/unit/test_talents_phase1b_ranks_and_hash.c AND NOT TARGET test_talents_phase1b_ranks_and_hash)
    add_executable(test_talents_phase1b_ranks_and_hash unit/test_talents_phase1b_ranks_and_hash.c)
    target_link_libraries(test_talents_phase1b_ranks_and_hash PRIVATE rogue_core)
    if(TARGET SDL2::SDL2)
        target_link_libraries(test_talents_phase1b_ranks_and_hash PRIVATE SDL2::SDL2)
        target_compile_definitions(test_talents_phase1b_ranks_and_hash PRIVATE ROGUE_HAVE_SDL=1 SDL_MAIN_HANDLED=1)
    else()
        target_compile_definitions(test_talents_phase1b_ranks_and_hash PRIVATE SDL_MAIN_HANDLED=1)
    endif()
    add_test(NAME test_talents_phase1b_ranks_and_hash COMMAND test_talents_phase1b_ranks_and_hash)
endif()
