# UI test suite split from tests/CMakeLists.txt

# UI Phase 6.2 bars + AP smoothing test
if(EXISTS ${CMAKE_CURRENT_SOURCE_DIR}/unit/test_ui_phase6_bars_ap.c AND NOT TARGET test_ui_phase6_bars_ap)
    add_executable(test_ui_phase6_bars_ap unit/test_ui_phase6_bars_ap.c)
    target_link_libraries(test_ui_phase6_bars_ap PRIVATE rogue_core)
    if(ROGUE_ENABLE_SDL)
        target_compile_definitions(test_ui_phase6_bars_ap PRIVATE ROGUE_HAVE_SDL=1)
    endif()
    add_test(NAME test_ui_phase6_bars_ap COMMAND test_ui_phase6_bars_ap)
endif()

# UI Phase 6.3 buff belt test
if(EXISTS ${CMAKE_CURRENT_SOURCE_DIR}/unit/test_ui_phase6_buff_belt.c AND NOT TARGET test_ui_phase6_buff_belt)
    add_executable(test_ui_phase6_buff_belt unit/test_ui_phase6_buff_belt.c)
    target_link_libraries(test_ui_phase6_buff_belt PRIVATE rogue_core)
    if(ROGUE_ENABLE_SDL)
        target_compile_definitions(test_ui_phase6_buff_belt PRIVATE ROGUE_HAVE_SDL=1)
    endif()
    add_test(NAME test_ui_phase6_buff_belt COMMAND test_ui_phase6_buff_belt)
endif()

if(EXISTS ${CMAKE_CURRENT_SOURCE_DIR}/unit/test_ui_phase6_minimap_metrics_alerts.c AND NOT TARGET test_ui_phase6_minimap_metrics_alerts)
    add_executable(test_ui_phase6_minimap_metrics_alerts unit/test_ui_phase6_minimap_metrics_alerts.c)
    target_link_libraries(test_ui_phase6_minimap_metrics_alerts PRIVATE rogue_core)
    if(ROGUE_ENABLE_SDL)
        target_compile_definitions(test_ui_phase6_minimap_metrics_alerts PRIVATE ROGUE_HAVE_SDL=1)
    endif()
    add_test(NAME test_ui_phase6_minimap_metrics_alerts COMMAND test_ui_phase6_minimap_metrics_alerts)
endif()

if(EXISTS ${CMAKE_CURRENT_SOURCE_DIR}/unit/test_ui_phase7_theme.c AND NOT TARGET test_ui_phase7_theme)
    add_executable(test_ui_phase7_theme unit/test_ui_phase7_theme.c)
    target_link_libraries(test_ui_phase7_theme PRIVATE rogue_core)
    if(ROGUE_ENABLE_SDL)
        target_compile_definitions(test_ui_phase7_theme PRIVATE ROGUE_HAVE_SDL=1)
    endif()
    add_test(NAME test_ui_phase7_theme COMMAND test_ui_phase7_theme)
endif()

if(EXISTS ${CMAKE_CURRENT_SOURCE_DIR}/unit/test_ui_phase7_accessibility.c AND NOT TARGET test_ui_phase7_accessibility)
    add_executable(test_ui_phase7_accessibility unit/test_ui_phase7_accessibility.c)
    target_link_libraries(test_ui_phase7_accessibility PRIVATE rogue_core)
    if(ROGUE_ENABLE_SDL)
        target_compile_definitions(test_ui_phase7_accessibility PRIVATE ROGUE_HAVE_SDL=1)
    endif()
    add_test(NAME test_ui_phase7_accessibility COMMAND test_ui_phase7_accessibility)
endif()

if(EXISTS ${CMAKE_CURRENT_SOURCE_DIR}/unit/test_ui_phase8_animation.c AND NOT TARGET test_ui_phase8_animation)
    add_executable(test_ui_phase8_animation unit/test_ui_phase8_animation.c)
    target_link_libraries(test_ui_phase8_animation PRIVATE rogue_core)
    if(ROGUE_ENABLE_SDL)
        target_compile_definitions(test_ui_phase8_animation PRIVATE ROGUE_HAVE_SDL=1)
    endif()
    add_test(NAME test_ui_phase8_animation COMMAND test_ui_phase8_animation)
endif()

if(EXISTS ${CMAKE_CURRENT_SOURCE_DIR}/unit/test_ui_phase8_timeline.c AND NOT TARGET test_ui_phase8_timeline)
    add_executable(test_ui_phase8_timeline unit/test_ui_phase8_timeline.c)
    target_link_libraries(test_ui_phase8_timeline PRIVATE rogue_core)
    if(ROGUE_ENABLE_SDL)
        target_compile_definitions(test_ui_phase8_timeline PRIVATE ROGUE_HAVE_SDL=1)
    endif()
    add_test(NAME test_ui_phase8_timeline COMMAND test_ui_phase8_timeline)
endif()

if(EXISTS ${CMAKE_CURRENT_SOURCE_DIR}/unit/test_ui_phase9_perf_virtual.c AND NOT TARGET test_ui_phase9_perf_virtual)
    add_executable(test_ui_phase9_perf_virtual unit/test_ui_phase9_perf_virtual.c)
    target_link_libraries(test_ui_phase9_perf_virtual PRIVATE rogue_core)
    if(ROGUE_ENABLE_SDL)
        target_compile_definitions(test_ui_phase9_perf_virtual PRIVATE ROGUE_HAVE_SDL=1)
    endif()
    add_test(NAME test_ui_phase9_perf_virtual COMMAND test_ui_phase9_perf_virtual)
endif()

if(EXISTS ${CMAKE_CURRENT_SOURCE_DIR}/unit/test_ui_phase9_extended.c AND NOT TARGET test_ui_phase9_extended)
    add_executable(test_ui_phase9_extended unit/test_ui_phase9_extended.c)
    target_link_libraries(test_ui_phase9_extended PRIVATE rogue_core)
    if(ROGUE_ENABLE_SDL)
        target_compile_definitions(test_ui_phase9_extended PRIVATE ROGUE_HAVE_SDL=1)
    endif()
    add_test(NAME test_ui_phase9_extended COMMAND test_ui_phase9_extended)
endif()

if(EXISTS ${CMAKE_CURRENT_SOURCE_DIR}/unit/test_ui_phase9_virtual_inventory.c AND NOT TARGET test_ui_phase9_virtual_inventory)
    add_executable(test_ui_phase9_virtual_inventory unit/test_ui_phase9_virtual_inventory.c)
    target_link_libraries(test_ui_phase9_virtual_inventory PRIVATE rogue_core)
    if(ROGUE_ENABLE_SDL)
        target_compile_definitions(test_ui_phase9_virtual_inventory PRIVATE ROGUE_HAVE_SDL=1)
    endif()
    add_test(NAME test_ui_phase9_virtual_inventory COMMAND test_ui_phase9_virtual_inventory)
endif()

# UI Phase 10.1 headless harness test
if(EXISTS ${CMAKE_CURRENT_SOURCE_DIR}/unit/test_ui_phase10_headless_harness.c AND NOT TARGET test_ui_phase10_headless_harness)
    add_executable(test_ui_phase10_headless_harness unit/test_ui_phase10_headless_harness.c)
    target_link_libraries(test_ui_phase10_headless_harness PRIVATE rogue_core)
    if(ROGUE_ENABLE_SDL)
        target_compile_definitions(test_ui_phase10_headless_harness PRIVATE ROGUE_HAVE_SDL=1)
    endif()
    add_test(NAME test_ui_phase10_headless_harness COMMAND test_ui_phase10_headless_harness)
endif()

if(EXISTS ${CMAKE_CURRENT_SOURCE_DIR}/unit/test_ui_phase10_golden_theming.c AND NOT TARGET test_ui_phase10_golden_theming)
    add_executable(test_ui_phase10_golden_theming unit/test_ui_phase10_golden_theming.c)
    target_link_libraries(test_ui_phase10_golden_theming PRIVATE rogue_core)
    if(ROGUE_ENABLE_SDL)
        target_compile_definitions(test_ui_phase10_golden_theming PRIVATE ROGUE_HAVE_SDL=1)
    endif()
    add_test(NAME test_ui_phase10_golden_theming COMMAND test_ui_phase10_golden_theming)
endif()

if(EXISTS ${CMAKE_CURRENT_SOURCE_DIR}/unit/test_ui_phase10_layout_fuzz.c AND NOT TARGET test_ui_phase10_layout_fuzz)
    add_executable(test_ui_phase10_layout_fuzz unit/test_ui_phase10_layout_fuzz.c)
    target_link_libraries(test_ui_phase10_layout_fuzz PRIVATE rogue_core)
    if(ROGUE_ENABLE_SDL)
        target_compile_definitions(test_ui_phase10_layout_fuzz PRIVATE ROGUE_HAVE_SDL=1)
    endif()
    add_test(NAME test_ui_phase10_layout_fuzz COMMAND test_ui_phase10_layout_fuzz)
endif()

if(EXISTS ${CMAKE_CURRENT_SOURCE_DIR}/unit/test_ui_phase10_perf_smoke.c AND NOT TARGET test_ui_phase10_perf_smoke)
    add_executable(test_ui_phase10_perf_smoke unit/test_ui_phase10_perf_smoke.c)
    target_link_libraries(test_ui_phase10_perf_smoke PRIVATE rogue_core)
    if(ROGUE_ENABLE_SDL)
        target_compile_definitions(test_ui_phase10_perf_smoke PRIVATE ROGUE_HAVE_SDL=1)
    endif()
    add_test(NAME test_ui_phase10_perf_smoke COMMAND test_ui_phase10_perf_smoke)
endif()

# UI Phase 10.3 navigation traversal test
if(EXISTS ${CMAKE_CURRENT_SOURCE_DIR}/unit/test_ui_phase10_navigation_traversal.c AND NOT TARGET test_ui_phase10_navigation_traversal)
    add_executable(test_ui_phase10_navigation_traversal unit/test_ui_phase10_navigation_traversal.c)
    target_link_libraries(test_ui_phase10_navigation_traversal PRIVATE rogue_core)
    if(ROGUE_ENABLE_SDL)
        target_compile_definitions(test_ui_phase10_navigation_traversal PRIVATE ROGUE_HAVE_SDL=1)
    endif()
    add_test(NAME test_ui_phase10_navigation_traversal COMMAND test_ui_phase10_navigation_traversal)
endif()

# UI Phase 11 docs & tooling test
if(EXISTS ${CMAKE_CURRENT_SOURCE_DIR}/unit/test_ui_phase11_docs_tooling.c AND NOT TARGET test_ui_phase11_docs_tooling)
    add_executable(test_ui_phase11_docs_tooling unit/test_ui_phase11_docs_tooling.c)
    target_link_libraries(test_ui_phase11_docs_tooling PRIVATE rogue_core)
    if(ROGUE_ENABLE_SDL)
        target_compile_definitions(test_ui_phase11_docs_tooling PRIVATE ROGUE_HAVE_SDL=1)
    endif()
    add_test(NAME test_ui_phase11_docs_tooling COMMAND test_ui_phase11_docs_tooling)
endif()

# UI Phase 4.x and 5.x blocks
if(EXISTS ${CMAKE_CURRENT_SOURCE_DIR}/unit/test_ui_phase4_context_menu.c AND NOT TARGET test_ui_phase4_context_menu)
    add_executable(test_ui_phase4_context_menu unit/test_ui_phase4_context_menu.c)
    target_link_libraries(test_ui_phase4_context_menu PRIVATE rogue_core)
    if(ROGUE_ENABLE_SDL)
        target_compile_definitions(test_ui_phase4_context_menu PRIVATE ROGUE_HAVE_SDL=1)
    endif()
    add_test(NAME test_ui_phase4_context_menu COMMAND test_ui_phase4_context_menu)
endif()

if(EXISTS ${CMAKE_CURRENT_SOURCE_DIR}/unit/test_ui_phase4_stat_preview.c AND NOT TARGET test_ui_phase4_stat_preview)
    add_executable(test_ui_phase4_stat_preview unit/test_ui_phase4_stat_preview.c)
    target_link_libraries(test_ui_phase4_stat_preview PRIVATE rogue_core)
    if(ROGUE_ENABLE_SDL)
        target_compile_definitions(test_ui_phase4_stat_preview PRIVATE ROGUE_HAVE_SDL=1)
    endif()
    add_test(NAME test_ui_phase4_stat_preview COMMAND test_ui_phase4_stat_preview)
endif()

if(EXISTS ${CMAKE_CURRENT_SOURCE_DIR}/unit/test_ui_phase4_rarity_colors.c AND NOT TARGET test_ui_phase4_rarity_colors)
    add_executable(test_ui_phase4_rarity_colors unit/test_ui_phase4_rarity_colors.c)
    target_link_libraries(test_ui_phase4_rarity_colors PRIVATE rogue_core)
    if(ROGUE_ENABLE_SDL)
        target_compile_definitions(test_ui_phase4_rarity_colors PRIVATE ROGUE_HAVE_SDL=1)
    endif()
    add_test(NAME test_ui_phase4_rarity_colors COMMAND test_ui_phase4_rarity_colors)
endif()

if(EXISTS ${CMAKE_CURRENT_SOURCE_DIR}/unit/test_ui_phase4_vendor_restock.c AND NOT TARGET test_ui_phase4_vendor_restock)
    add_executable(test_ui_phase4_vendor_restock unit/test_ui_phase4_vendor_restock.c)
    target_link_libraries(test_ui_phase4_vendor_restock PRIVATE rogue_core)
    if(ROGUE_ENABLE_SDL)
        target_compile_definitions(test_ui_phase4_vendor_restock PRIVATE ROGUE_HAVE_SDL=1)
    endif()
    add_test(NAME test_ui_phase4_vendor_restock COMMAND test_ui_phase4_vendor_restock)
endif()

if(EXISTS ${CMAKE_CURRENT_SOURCE_DIR}/unit/test_ui_phase4_vendor_transaction.c AND NOT TARGET test_ui_phase4_vendor_transaction)
    add_executable(test_ui_phase4_vendor_transaction unit/test_ui_phase4_vendor_transaction.c)
    target_link_libraries(test_ui_phase4_vendor_transaction PRIVATE rogue_core)
    if(ROGUE_ENABLE_SDL)
        target_compile_definitions(test_ui_phase4_vendor_transaction PRIVATE ROGUE_HAVE_SDL=1)
    endif()
    add_test(NAME test_ui_phase4_vendor_transaction COMMAND test_ui_phase4_vendor_transaction)
endif()

if(EXISTS ${CMAKE_CURRENT_SOURCE_DIR}/unit/test_ui_phase4_durability_thresholds.c AND NOT TARGET test_ui_phase4_durability_thresholds)
    add_executable(test_ui_phase4_durability_thresholds unit/test_ui_phase4_durability_thresholds.c)
    target_link_libraries(test_ui_phase4_durability_thresholds PRIVATE rogue_core)
    if(ROGUE_ENABLE_SDL)
        target_compile_definitions(test_ui_phase4_durability_thresholds PRIVATE ROGUE_HAVE_SDL=1)
    endif()
    add_test(NAME test_ui_phase4_durability_thresholds COMMAND test_ui_phase4_durability_thresholds)
endif()

if(EXISTS ${CMAKE_CURRENT_SOURCE_DIR}/unit/test_ui_phase4_radial_selector.c AND NOT TARGET test_ui_phase4_radial_selector)
    add_executable(test_ui_phase4_radial_selector unit/test_ui_phase4_radial_selector.c)
    target_link_libraries(test_ui_phase4_radial_selector PRIVATE rogue_core)
    if(ROGUE_ENABLE_SDL)
        target_compile_definitions(test_ui_phase4_radial_selector PRIVATE ROGUE_HAVE_SDL=1)
    endif()
    add_test(NAME test_ui_phase4_radial_selector COMMAND test_ui_phase4_radial_selector)
endif()

if(EXISTS ${CMAKE_CURRENT_SOURCE_DIR}/unit/test_ui_phase5_skillgraph.c AND NOT TARGET test_ui_phase5_skillgraph)
    add_executable(test_ui_phase5_skillgraph unit/test_ui_phase5_skillgraph.c)
    target_link_libraries(test_ui_phase5_skillgraph PRIVATE rogue_core)
    if(ROGUE_ENABLE_SDL)
        target_compile_definitions(test_ui_phase5_skillgraph PRIVATE ROGUE_HAVE_SDL=1)
    endif()
    add_test(NAME test_ui_phase5_skillgraph COMMAND test_ui_phase5_skillgraph)
endif()

if(EXISTS ${CMAKE_CURRENT_SOURCE_DIR}/unit/test_ui_skill_maze_generation.c AND NOT TARGET test_ui_skill_maze_generation)
    add_executable(test_ui_skill_maze_generation unit/test_ui_skill_maze_generation.c)
    target_link_libraries(test_ui_skill_maze_generation PRIVATE rogue_core)
    if(ROGUE_ENABLE_SDL)
        target_compile_definitions(test_ui_skill_maze_generation PRIVATE ROGUE_HAVE_SDL=1)
    endif()
    add_test(NAME test_ui_skill_maze_generation COMMAND test_ui_skill_maze_generation)
endif()

if(EXISTS ${CMAKE_CURRENT_SOURCE_DIR}/unit/test_ui_phase5_skillgraph_anim.c AND NOT TARGET test_ui_phase5_skillgraph_anim)
    add_executable(test_ui_phase5_skillgraph_anim unit/test_ui_phase5_skillgraph_anim.c)
    target_link_libraries(test_ui_phase5_skillgraph_anim PRIVATE rogue_core)
    if(ROGUE_ENABLE_SDL)
        target_compile_definitions(test_ui_phase5_skillgraph_anim PRIVATE ROGUE_HAVE_SDL=1)
    endif()
    add_test(NAME test_ui_phase5_skillgraph_anim COMMAND test_ui_phase5_skillgraph_anim)
endif()
