# ====================================================
# Vendor System Tests
# ====================================================

# Vendor System Phase 0 valuation & catalog test (0.1-0.3,0.5)
if(EXISTS ${CMAKE_CURRENT_SOURCE_DIR}/unit/test_vendor_phase0_value.c AND NOT TARGET test_vendor_phase0_value)
    add_executable(test_vendor_phase0_value unit/test_vendor_phase0_value.c)
    target_link_libraries(test_vendor_phase0_value PRIVATE rogue_core)
    if(ROGUE_ENABLE_SDL)
        target_compile_definitions(test_vendor_phase0_value PRIVATE ROGUE_HAVE_SDL=1)
    endif()
    add_test(NAME test_vendor_phase0_value COMMAND test_vendor_phase0_value)
endif()

# Vendor System Phase 0 inflow baseline simulation test (0.4)
if(EXISTS ${CMAKE_CURRENT_SOURCE_DIR}/unit/test_vendor_phase0_inflow.c AND NOT TARGET test_vendor_phase0_inflow)
    add_executable(test_vendor_phase0_inflow unit/test_vendor_phase0_inflow.c)
    target_link_libraries(test_vendor_phase0_inflow PRIVATE rogue_core)
    if(ROGUE_ENABLE_SDL)
        target_compile_definitions(test_vendor_phase0_inflow PRIVATE ROGUE_HAVE_SDL=1)
    endif()
    add_test(NAME test_vendor_phase0_inflow COMMAND test_vendor_phase0_inflow)
endif()

# Vendor System Phase 1 registry test (1.1-1.3)
if(EXISTS ${CMAKE_CURRENT_SOURCE_DIR}/unit/test_vendor_phase1_registry.c AND NOT TARGET test_vendor_phase1_registry)
    add_executable(test_vendor_phase1_registry unit/test_vendor_phase1_registry.c)
    target_link_libraries(test_vendor_phase1_registry PRIVATE rogue_core)
    if(ROGUE_ENABLE_SDL)
        target_compile_definitions(test_vendor_phase1_registry PRIVATE ROGUE_HAVE_SDL=1)
    endif()
    add_test(NAME test_vendor_phase1_registry COMMAND test_vendor_phase1_registry)
endif()

# Vendor System Phase 1 negotiation & rule tests (1.4 + remainder 1.5)
if(EXISTS ${CMAKE_CURRENT_SOURCE_DIR}/unit/test_vendor_phase1_negotiation.c AND NOT TARGET test_vendor_phase1_negotiation)
    add_executable(test_vendor_phase1_negotiation unit/test_vendor_phase1_negotiation.c)
    target_link_libraries(test_vendor_phase1_negotiation PRIVATE rogue_core)
    if(ROGUE_ENABLE_SDL)
        target_compile_definitions(test_vendor_phase1_negotiation PRIVATE ROGUE_HAVE_SDL=1)
    endif()
    add_test(NAME test_vendor_phase1_negotiation COMMAND test_vendor_phase1_negotiation)
endif()

# Vendor System Phase 2 inventory management test
if(EXISTS ${CMAKE_CURRENT_SOURCE_DIR}/unit/test_vendor_phase2_inventory.c AND NOT TARGET test_vendor_phase2_inventory)
    add_executable(test_vendor_phase2_inventory unit/test_vendor_phase2_inventory.c)
    target_link_libraries(test_vendor_phase2_inventory PRIVATE rogue_core)
    if(TARGET SDL2::SDL2)
        target_link_libraries(test_vendor_phase2_inventory PRIVATE SDL2::SDL2)
        target_compile_definitions(test_vendor_phase2_inventory PRIVATE ROGUE_HAVE_SDL=1)
    endif()
    add_test(NAME test_vendor_phase2_inventory COMMAND test_vendor_phase2_inventory)
endif()

# Vendor System Phase 2 constrained inventory test
if(EXISTS ${CMAKE_CURRENT_SOURCE_DIR}/unit/test_vendor_phase2_constrained.c AND NOT TARGET test_vendor_phase2_constrained)
    add_executable(test_vendor_phase2_constrained unit/test_vendor_phase2_constrained.c)
    target_link_libraries(test_vendor_phase2_constrained PRIVATE rogue_core)
    if(TARGET SDL2::SDL2)
        target_link_libraries(test_vendor_phase2_constrained PRIVATE SDL2::SDL2)
        target_compile_definitions(test_vendor_phase2_constrained PRIVATE ROGUE_HAVE_SDL=1)
    endif()
    add_test(NAME test_vendor_phase2_constrained COMMAND test_vendor_phase2_constrained)
endif()

# Vendor System Phase 3 pricing test
if(EXISTS ${CMAKE_CURRENT_SOURCE_DIR}/unit/test_vendor_phase3_pricing.c AND NOT TARGET test_vendor_phase3_pricing)
    add_executable(test_vendor_phase3_pricing unit/test_vendor_phase3_pricing.c)
    target_link_libraries(test_vendor_phase3_pricing PRIVATE rogue_core)
    if(TARGET SDL2::SDL2)
        target_link_libraries(test_vendor_phase3_pricing PRIVATE SDL2::SDL2)
        target_compile_definitions(test_vendor_phase3_pricing PRIVATE ROGUE_HAVE_SDL=1)
    endif()
    add_test(NAME test_vendor_phase3_pricing COMMAND test_vendor_phase3_pricing)
endif()

# Vendor System Phase 4 reputation & negotiation test
if(EXISTS ${CMAKE_CURRENT_SOURCE_DIR}/unit/test_vendor_phase4_reputation_negotiation.c AND NOT TARGET test_vendor_phase4_reputation_negotiation)
    add_executable(test_vendor_phase4_reputation_negotiation unit/test_vendor_phase4_reputation_negotiation.c)
    target_link_libraries(test_vendor_phase4_reputation_negotiation PRIVATE rogue_core)
    if(TARGET SDL2::SDL2)
        target_link_libraries(test_vendor_phase4_reputation_negotiation PRIVATE SDL2::SDL2)
        target_compile_definitions(test_vendor_phase4_reputation_negotiation PRIVATE ROGUE_HAVE_SDL=1)
    endif()
    add_test(NAME test_vendor_phase4_reputation_negotiation COMMAND test_vendor_phase4_reputation_negotiation)
endif()

# Vendor System Phase 5 buyback journal test
if(EXISTS ${CMAKE_CURRENT_SOURCE_DIR}/unit/test_vendor_phase5_buyback_journal.c AND NOT TARGET test_vendor_phase5_buyback_journal)
    add_executable(test_vendor_phase5_buyback_journal unit/test_vendor_phase5_buyback_journal.c)
    target_link_libraries(test_vendor_phase5_buyback_journal PRIVATE rogue_core)
    if(TARGET SDL2::SDL2)
        target_link_libraries(test_vendor_phase5_buyback_journal PRIVATE SDL2::SDL2)
        target_compile_definitions(test_vendor_phase5_buyback_journal PRIVATE ROGUE_HAVE_SDL=1)
    endif()
    add_test(NAME test_vendor_phase5_buyback_journal COMMAND test_vendor_phase5_buyback_journal)
endif()

# Vendor System Phase 6 special offers test
if(EXISTS ${CMAKE_CURRENT_SOURCE_DIR}/unit/test_vendor_phase6_special_offers.c AND NOT TARGET test_vendor_phase6_special_offers)
    add_executable(test_vendor_phase6_special_offers unit/test_vendor_phase6_special_offers.c)
    target_link_libraries(test_vendor_phase6_special_offers PRIVATE rogue_core)
    if(TARGET SDL2::SDL2)
        target_link_libraries(test_vendor_phase6_special_offers PRIVATE SDL2::SDL2)
        target_compile_definitions(test_vendor_phase6_special_offers PRIVATE ROGUE_HAVE_SDL=1)
    endif()
    add_test(NAME test_vendor_phase6_special_offers COMMAND test_vendor_phase6_special_offers)
endif()

# Vendor System Phase 7 sinks test
if(EXISTS ${CMAKE_CURRENT_SOURCE_DIR}/unit/test_vendor_phase7_sinks.c AND NOT TARGET test_vendor_phase7_sinks)
    add_executable(test_vendor_phase7_sinks unit/test_vendor_phase7_sinks.c)
    target_link_libraries(test_vendor_phase7_sinks PRIVATE rogue_core)
    if(TARGET SDL2::SDL2)
        target_link_libraries(test_vendor_phase7_sinks PRIVATE SDL2::SDL2)
        target_compile_definitions(test_vendor_phase7_sinks PRIVATE ROGUE_HAVE_SDL=1)
    endif()
    add_test(NAME test_vendor_phase7_sinks COMMAND test_vendor_phase7_sinks)
endif()

# Vendor System Phase 8 crafting integration test
if(EXISTS ${CMAKE_CURRENT_SOURCE_DIR}/unit/test_vendor_phase8_crafting_integration.c AND NOT TARGET test_vendor_phase8_crafting_integration)
    add_executable(test_vendor_phase8_crafting_integration unit/test_vendor_phase8_crafting_integration.c)
    target_link_libraries(test_vendor_phase8_crafting_integration PRIVATE rogue_core)
    if(TARGET SDL2::SDL2)
        target_link_libraries(test_vendor_phase8_crafting_integration PRIVATE SDL2::SDL2)
        target_compile_definitions(test_vendor_phase8_crafting_integration PRIVATE ROGUE_HAVE_SDL=1)
    endif()
    add_test(NAME test_vendor_phase8_crafting_integration COMMAND test_vendor_phase8_crafting_integration)
endif()

# Vendor System Phase 9 adaptive pricing test
if(EXISTS ${CMAKE_CURRENT_SOURCE_DIR}/unit/test_vendor_phase9_adaptive.c AND NOT TARGET test_vendor_phase9_adaptive)
    add_executable(test_vendor_phase9_adaptive unit/test_vendor_phase9_adaptive.c)
    target_link_libraries(test_vendor_phase9_adaptive PRIVATE rogue_core)
    if(TARGET SDL2::SDL2)
        target_link_libraries(test_vendor_phase9_adaptive PRIVATE SDL2::SDL2)
        target_compile_definitions(test_vendor_phase9_adaptive PRIVATE ROGUE_HAVE_SDL=1)
    endif()
    add_test(NAME test_vendor_phase9_adaptive COMMAND test_vendor_phase9_adaptive)
endif()

# Vendor System Phase 10 balancing test
if(EXISTS ${CMAKE_CURRENT_SOURCE_DIR}/unit/test_vendor_phase10_balancing.c AND NOT TARGET test_vendor_phase10_balancing)
    add_executable(test_vendor_phase10_balancing unit/test_vendor_phase10_balancing.c)
    target_link_libraries(test_vendor_phase10_balancing PRIVATE rogue_core)
    if(TARGET SDL2::SDL2)
        target_link_libraries(test_vendor_phase10_balancing PRIVATE SDL2::SDL2)
        target_compile_definitions(test_vendor_phase10_balancing PRIVATE ROGUE_HAVE_SDL=1)
    endif()
    add_test(NAME test_vendor_phase10_balancing COMMAND test_vendor_phase10_balancing)
endif()

# Vendor System Phase 11 performance test
if(EXISTS ${CMAKE_CURRENT_SOURCE_DIR}/unit/test_vendor_phase11_perf.c AND NOT TARGET test_vendor_phase11_perf)
    add_executable(test_vendor_phase11_perf unit/test_vendor_phase11_perf.c)
    target_link_libraries(test_vendor_phase11_perf PRIVATE rogue_core)
    if(TARGET SDL2::SDL2)
        target_link_libraries(test_vendor_phase11_perf PRIVATE SDL2::SDL2)
        target_compile_definitions(test_vendor_phase11_perf PRIVATE ROGUE_HAVE_SDL=1)
    endif()
    add_test(NAME test_vendor_phase11_perf COMMAND test_vendor_phase11_perf)
endif()

# Vendor System Phase 12 determinism test
if(EXISTS ${CMAKE_CURRENT_SOURCE_DIR}/unit/test_vendor_phase12_determinism.c AND NOT TARGET test_vendor_phase12_determinism)
    add_executable(test_vendor_phase12_determinism unit/test_vendor_phase12_determinism.c)
    target_link_libraries(test_vendor_phase12_determinism PRIVATE rogue_core)
    if(TARGET SDL2::SDL2)
        target_link_libraries(test_vendor_phase12_determinism PRIVATE SDL2::SDL2)
        target_compile_definitions(test_vendor_phase12_determinism PRIVATE ROGUE_HAVE_SDL=1)
    endif()
    add_test(NAME test_vendor_phase12_determinism COMMAND test_vendor_phase12_determinism)
endif()

# Vendor System Phase 13 compaction test
if(EXISTS ${CMAKE_CURRENT_SOURCE_DIR}/unit/test_vendor_phase13_compaction.c AND NOT TARGET test_vendor_phase13_compaction)
    add_executable(test_vendor_phase13_compaction unit/test_vendor_phase13_compaction.c)
    target_link_libraries(test_vendor_phase13_compaction PRIVATE rogue_core)
    if(ROGUE_ENABLE_SDL)
        if(TARGET SDL2::SDL2)
            target_link_libraries(test_vendor_phase13_compaction PRIVATE SDL2::SDL2)
            target_compile_definitions(test_vendor_phase13_compaction PRIVATE ROGUE_HAVE_SDL=1)
        endif()
    endif()
    add_test(NAME test_vendor_phase13_compaction COMMAND test_vendor_phase13_compaction)
endif()

# Vendor basic inventory test
if(EXISTS ${CMAKE_CURRENT_SOURCE_DIR}/unit/test_vendor_inventory.c AND NOT TARGET test_vendor_inventory)
    add_executable(test_vendor_inventory unit/test_vendor_inventory.c)
    target_link_libraries(test_vendor_inventory PRIVATE rogue_core)
    if(ROGUE_ENABLE_SDL)
        target_compile_definitions(test_vendor_inventory PRIVATE ROGUE_HAVE_SDL=1)
    endif()
    add_test(NAME test_vendor_inventory COMMAND test_vendor_inventory)
endif()

# Vendor restock rotation test (10.3)
if(EXISTS ${CMAKE_CURRENT_SOURCE_DIR}/unit/test_vendor_restock.c AND NOT TARGET test_vendor_restock)
    add_executable(test_vendor_restock unit/test_vendor_restock.c)
    target_link_libraries(test_vendor_restock PRIVATE rogue_core)
    if(ROGUE_ENABLE_SDL)
        target_compile_definitions(test_vendor_restock PRIVATE ROGUE_HAVE_SDL=1)
    endif()
    add_test(NAME test_vendor_restock COMMAND test_vendor_restock)
endif()
