repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v18.1.5
    hooks:
      - id: clang-format
        types_or: [c, c++]
        args: [-style=file]
  - repo: local
    hooks:
      - id: clang-tidy-optional
        name: (Optional) clang-tidy analysis
        entry: python tools/precommit/clang_tidy_wrapper.py
        language: system
        pass_filenames: false
        stages: [manual]
      - id: clang-tidy-optional
        name: (Optional) clang-tidy (manual) – use for deeper review locally
        entry: python tools/precommit/clang_tidy_wrapper.py
        language: system
        pass_filenames: false
        stages: [manual]

default_language_version:
  python: python3

ci:
  autoupdate_schedule: quarterly
