#ifndef ROGUE_CORE_FEATURES_H
#define ROGUE_CORE_FEATURES_H
/* Central feature capability macros (Phase M2.2) */
#define ROGUE_FEATURE_COMBAT 1
#define ROGUE_FEATURE_DAMAGE_EVENTS 1
#define ROGUE_FEATURE_COMBAT_OBSERVER 1
#define ROGUE_FEATURE_PERSISTENCE 1
#define ROGUE_FEATURE_PROJECTILES 1
#endif
