# CMake generated Testfile for 
# Source directory: /home/runner/work/Roguelike/Roguelike
# Build directory: /home/runner/work/Roguelike/Roguelike/build_test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[asset_validation_cli]=] "/home/runner/work/Roguelike/Roguelike/build_test/asset_validate" "--manifest" "/home/runner/work/Roguelike/Roguelike/build_test/asset_manifest_ctest.txt" "--optimize")
set_tests_properties([=[asset_validation_cli]=] PROPERTIES  WORKING_DIRECTORY "/home/runner/work/Roguelike/Roguelike" _BACKTRACE_TRIPLES "/home/runner/work/Roguelike/Roguelike/CMakeLists.txt;633;add_test;/home/runner/work/Roguelike/Roguelike/CMakeLists.txt;661;rogue_add_test;/home/runner/work/Roguelike/Roguelike/CMakeLists.txt;0;")
add_test([=[asset_tool_stats_cli]=] "/home/runner/work/Roguelike/Roguelike/build_test/asset_tool" "stats")
set_tests_properties([=[asset_tool_stats_cli]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/Roguelike/Roguelike/CMakeLists.txt;633;add_test;/home/runner/work/Roguelike/Roguelike/CMakeLists.txt;666;rogue_add_test;/home/runner/work/Roguelike/Roguelike/CMakeLists.txt;0;")
add_test([=[test_skills_phase2_api]=] "/home/runner/work/Roguelike/Roguelike/build_test/test_skills_phase2_api")
set_tests_properties([=[test_skills_phase2_api]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/Roguelike/Roguelike/CMakeLists.txt;633;add_test;/home/runner/work/Roguelike/Roguelike/CMakeLists.txt;1077;rogue_add_test;/home/runner/work/Roguelike/Roguelike/CMakeLists.txt;0;")
add_test([=[test_skills_phase1_3_execution_pathways]=] "/home/runner/work/Roguelike/Roguelike/build_test/test_skills_phase1_3_execution_pathways")
set_tests_properties([=[test_skills_phase1_3_execution_pathways]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/Roguelike/Roguelike/CMakeLists.txt;633;add_test;/home/runner/work/Roguelike/Roguelike/CMakeLists.txt;1085;rogue_add_test;/home/runner/work/Roguelike/Roguelike/CMakeLists.txt;0;")
add_test([=[test_skills_rotation_sim]=] "/home/runner/work/Roguelike/Roguelike/build_test/test_skills_rotation_sim")
set_tests_properties([=[test_skills_rotation_sim]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/Roguelike/Roguelike/CMakeLists.txt;633;add_test;/home/runner/work/Roguelike/Roguelike/CMakeLists.txt;1092;rogue_add_test;/home/runner/work/Roguelike/Roguelike/CMakeLists.txt;0;")
add_test([=[test_overlay_core]=] "/home/runner/work/Roguelike/Roguelike/build_test/test_overlay_core")
set_tests_properties([=[test_overlay_core]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/Roguelike/Roguelike/CMakeLists.txt;633;add_test;/home/runner/work/Roguelike/Roguelike/CMakeLists.txt;1099;rogue_add_test;/home/runner/work/Roguelike/Roguelike/CMakeLists.txt;0;")
add_test([=[test_overlay_widgets]=] "/home/runner/work/Roguelike/Roguelike/build_test/test_overlay_widgets")
set_tests_properties([=[test_overlay_widgets]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/Roguelike/Roguelike/CMakeLists.txt;633;add_test;/home/runner/work/Roguelike/Roguelike/CMakeLists.txt;1107;rogue_add_test;/home/runner/work/Roguelike/Roguelike/CMakeLists.txt;0;")
add_test([=[test_overlay_widgets_advanced]=] "/home/runner/work/Roguelike/Roguelike/build_test/test_overlay_widgets_advanced")
set_tests_properties([=[test_overlay_widgets_advanced]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/Roguelike/Roguelike/CMakeLists.txt;633;add_test;/home/runner/work/Roguelike/Roguelike/CMakeLists.txt;1109;rogue_add_test;/home/runner/work/Roguelike/Roguelike/CMakeLists.txt;0;")
add_test([=[test_overlay_multiselect_list]=] "/home/runner/work/Roguelike/Roguelike/build_test/test_overlay_multiselect_list")
set_tests_properties([=[test_overlay_multiselect_list]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/Roguelike/Roguelike/CMakeLists.txt;633;add_test;/home/runner/work/Roguelike/Roguelike/CMakeLists.txt;1115;rogue_add_test;/home/runner/work/Roguelike/Roguelike/CMakeLists.txt;0;")
add_test([=[test_overlay_table_widget]=] "/home/runner/work/Roguelike/Roguelike/build_test/test_overlay_table_widget")
set_tests_properties([=[test_overlay_table_widget]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/Roguelike/Roguelike/CMakeLists.txt;633;add_test;/home/runner/work/Roguelike/Roguelike/CMakeLists.txt;1121;rogue_add_test;/home/runner/work/Roguelike/Roguelike/CMakeLists.txt;0;")
add_test([=[test_overlay_table_perf_smoke]=] "/home/runner/work/Roguelike/Roguelike/build_test/test_overlay_table_perf_smoke")
set_tests_properties([=[test_overlay_table_perf_smoke]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/Roguelike/Roguelike/CMakeLists.txt;633;add_test;/home/runner/work/Roguelike/Roguelike/CMakeLists.txt;1128;rogue_add_test;/home/runner/work/Roguelike/Roguelike/CMakeLists.txt;0;")
add_test([=[test_tag_registry_validate]=] "/home/runner/work/Roguelike/Roguelike/build_test/test_tag_registry_validate")
set_tests_properties([=[test_tag_registry_validate]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/Roguelike/Roguelike/CMakeLists.txt;633;add_test;/home/runner/work/Roguelike/Roguelike/CMakeLists.txt;1134;rogue_add_test;/home/runner/work/Roguelike/Roguelike/CMakeLists.txt;0;")
add_test([=[test_json_io]=] "/home/runner/work/Roguelike/Roguelike/build_test/test_json_io")
set_tests_properties([=[test_json_io]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/Roguelike/Roguelike/CMakeLists.txt;633;add_test;/home/runner/work/Roguelike/Roguelike/CMakeLists.txt;1139;rogue_add_test;/home/runner/work/Roguelike/Roguelike/CMakeLists.txt;0;")
add_test([=[test_json_envelope]=] "/home/runner/work/Roguelike/Roguelike/build_test/test_json_envelope")
set_tests_properties([=[test_json_envelope]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/Roguelike/Roguelike/CMakeLists.txt;633;add_test;/home/runner/work/Roguelike/Roguelike/CMakeLists.txt;1144;rogue_add_test;/home/runner/work/Roguelike/Roguelike/CMakeLists.txt;0;")
add_test([=[test_entity_schema]=] "/home/runner/work/Roguelike/Roguelike/build_test/test_entity_schema")
set_tests_properties([=[test_entity_schema]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/Roguelike/Roguelike/CMakeLists.txt;633;add_test;/home/runner/work/Roguelike/Roguelike/CMakeLists.txt;1152;rogue_add_test;/home/runner/work/Roguelike/Roguelike/CMakeLists.txt;0;")
add_test([=[test_tilesets_schema]=] "/home/runner/work/Roguelike/Roguelike/build_test/test_tilesets_schema")
set_tests_properties([=[test_tilesets_schema]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/Roguelike/Roguelike/CMakeLists.txt;633;add_test;/home/runner/work/Roguelike/Roguelike/CMakeLists.txt;1160;rogue_add_test;/home/runner/work/Roguelike/Roguelike/CMakeLists.txt;0;")
add_test([=[test_items_schema]=] "/home/runner/work/Roguelike/Roguelike/build_test/test_items_schema")
set_tests_properties([=[test_items_schema]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/Roguelike/Roguelike/CMakeLists.txt;633;add_test;/home/runner/work/Roguelike/Roguelike/CMakeLists.txt;1168;rogue_add_test;/home/runner/work/Roguelike/Roguelike/CMakeLists.txt;0;")
add_test([=[test_sprite_audio_schema]=] "/home/runner/work/Roguelike/Roguelike/build_test/test_sprite_audio_schema")
set_tests_properties([=[test_sprite_audio_schema]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/Roguelike/Roguelike/CMakeLists.txt;633;add_test;/home/runner/work/Roguelike/Roguelike/CMakeLists.txt;1176;rogue_add_test;/home/runner/work/Roguelike/Roguelike/CMakeLists.txt;0;")
add_test([=[test_asset_dep_rejects]=] "/home/runner/work/Roguelike/Roguelike/build_test/test_asset_dep_rejects")
set_tests_properties([=[test_asset_dep_rejects]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/Roguelike/Roguelike/CMakeLists.txt;633;add_test;/home/runner/work/Roguelike/Roguelike/CMakeLists.txt;1184;rogue_add_test;/home/runner/work/Roguelike/Roguelike/CMakeLists.txt;0;")
add_test([=[test_asset_classification]=] "/home/runner/work/Roguelike/Roguelike/build_test/test_asset_classification")
set_tests_properties([=[test_asset_classification]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/Roguelike/Roguelike/CMakeLists.txt;633;add_test;/home/runner/work/Roguelike/Roguelike/CMakeLists.txt;1192;rogue_add_test;/home/runner/work/Roguelike/Roguelike/CMakeLists.txt;0;")
add_test([=[test_asset_manager_basic]=] "/home/runner/work/Roguelike/Roguelike/build_test/test_asset_manager_basic")
set_tests_properties([=[test_asset_manager_basic]=] PROPERTIES  LABELS "asset" _BACKTRACE_TRIPLES "/home/runner/work/Roguelike/Roguelike/CMakeLists.txt;633;add_test;/home/runner/work/Roguelike/Roguelike/CMakeLists.txt;1200;rogue_add_test;/home/runner/work/Roguelike/Roguelike/CMakeLists.txt;0;")
add_test([=[test_asset_manager_phase6_streaming]=] "/home/runner/work/Roguelike/Roguelike/build_test/test_asset_manager_phase6_streaming")
set_tests_properties([=[test_asset_manager_phase6_streaming]=] PROPERTIES  LABELS "asset;perf" _BACKTRACE_TRIPLES "/home/runner/work/Roguelike/Roguelike/CMakeLists.txt;633;add_test;/home/runner/work/Roguelike/Roguelike/CMakeLists.txt;1209;rogue_add_test;/home/runner/work/Roguelike/Roguelike/CMakeLists.txt;0;")
add_test([=[test_asset_manager_phase6_compressed]=] "/home/runner/work/Roguelike/Roguelike/build_test/test_asset_manager_phase6_compressed")
set_tests_properties([=[test_asset_manager_phase6_compressed]=] PROPERTIES  LABELS "asset" _BACKTRACE_TRIPLES "/home/runner/work/Roguelike/Roguelike/CMakeLists.txt;633;add_test;/home/runner/work/Roguelike/Roguelike/CMakeLists.txt;1217;rogue_add_test;/home/runner/work/Roguelike/Roguelike/CMakeLists.txt;0;")
add_test([=[test_asset_manager_phase6_atlas]=] "/home/runner/work/Roguelike/Roguelike/build_test/test_asset_manager_phase6_atlas")
set_tests_properties([=[test_asset_manager_phase6_atlas]=] PROPERTIES  LABELS "asset" _BACKTRACE_TRIPLES "/home/runner/work/Roguelike/Roguelike/CMakeLists.txt;633;add_test;/home/runner/work/Roguelike/Roguelike/CMakeLists.txt;1223;rogue_add_test;/home/runner/work/Roguelike/Roguelike/CMakeLists.txt;0;")
add_test([=[test_asset_manager_resize_export]=] "/home/runner/work/Roguelike/Roguelike/build_test/test_asset_manager_resize_export")
set_tests_properties([=[test_asset_manager_resize_export]=] PROPERTIES  LABELS "asset" _BACKTRACE_TRIPLES "/home/runner/work/Roguelike/Roguelike/CMakeLists.txt;633;add_test;/home/runner/work/Roguelike/Roguelike/CMakeLists.txt;1229;rogue_add_test;/home/runner/work/Roguelike/Roguelike/CMakeLists.txt;0;")
add_test([=[test_asset_manager_resize_export_positive]=] "/home/runner/work/Roguelike/Roguelike/build_test/test_asset_manager_resize_export_positive")
set_tests_properties([=[test_asset_manager_resize_export_positive]=] PROPERTIES  LABELS "asset" _BACKTRACE_TRIPLES "/home/runner/work/Roguelike/Roguelike/CMakeLists.txt;633;add_test;/home/runner/work/Roguelike/Roguelike/CMakeLists.txt;1238;rogue_add_test;/home/runner/work/Roguelike/Roguelike/CMakeLists.txt;0;")
add_test([=[test_asset_phase7_usage_stats]=] "/home/runner/work/Roguelike/Roguelike/build_test/test_asset_phase7_usage_stats")
set_tests_properties([=[test_asset_phase7_usage_stats]=] PROPERTIES  LABELS "asset" _BACKTRACE_TRIPLES "/home/runner/work/Roguelike/Roguelike/CMakeLists.txt;633;add_test;/home/runner/work/Roguelike/Roguelike/CMakeLists.txt;1244;rogue_add_test;/home/runner/work/Roguelike/Roguelike/CMakeLists.txt;0;")
add_test([=[test_asset_phase7_tool_cli]=] "/home/runner/work/Roguelike/Roguelike/build_test/test_asset_phase7_tool_cli")
set_tests_properties([=[test_asset_phase7_tool_cli]=] PROPERTIES  LABELS "asset" _BACKTRACE_TRIPLES "/home/runner/work/Roguelike/Roguelike/CMakeLists.txt;633;add_test;/home/runner/work/Roguelike/Roguelike/CMakeLists.txt;1259;rogue_add_test;/home/runner/work/Roguelike/Roguelike/CMakeLists.txt;0;")
add_test([=[test_asset_manager_reload]=] "/home/runner/work/Roguelike/Roguelike/build_test/test_asset_manager_reload")
set_tests_properties([=[test_asset_manager_reload]=] PROPERTIES  LABELS "asset" _BACKTRACE_TRIPLES "/home/runner/work/Roguelike/Roguelike/CMakeLists.txt;1268;add_test;/home/runner/work/Roguelike/Roguelike/CMakeLists.txt;0;")
add_test([=[test_asset_placeholder_enforcement]=] "/home/runner/work/Roguelike/Roguelike/build_test/test_asset_placeholder_enforcement")
set_tests_properties([=[test_asset_placeholder_enforcement]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/Roguelike/Roguelike/CMakeLists.txt;1277;add_test;/home/runner/work/Roguelike/Roguelike/CMakeLists.txt;0;")
add_test([=[test_level_schema]=] "/home/runner/work/Roguelike/Roguelike/build_test/test_level_schema")
set_tests_properties([=[test_level_schema]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/Roguelike/Roguelike/CMakeLists.txt;1284;add_test;/home/runner/work/Roguelike/Roguelike/CMakeLists.txt;0;")
add_test([=[test_ui_theme_schema]=] "/home/runner/work/Roguelike/Roguelike/build_test/test_ui_theme_schema")
set_tests_properties([=[test_ui_theme_schema]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/Roguelike/Roguelike/CMakeLists.txt;1304;add_test;/home/runner/work/Roguelike/Roguelike/CMakeLists.txt;0;")
add_test([=[test_schema_versioning_basic]=] "/home/runner/work/Roguelike/Roguelike/build_test/test_schema_versioning_basic")
set_tests_properties([=[test_schema_versioning_basic]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/Roguelike/Roguelike/CMakeLists.txt;1305;add_test;/home/runner/work/Roguelike/Roguelike/CMakeLists.txt;0;")
add_test([=[test_skills_roundtrip_schema]=] "/home/runner/work/Roguelike/Roguelike/build_test/test_skills_roundtrip_schema")
set_tests_properties([=[test_skills_roundtrip_schema]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/Roguelike/Roguelike/CMakeLists.txt;1315;add_test;/home/runner/work/Roguelike/Roguelike/CMakeLists.txt;0;")
add_test([=[test_skills_live_reload]=] "/home/runner/work/Roguelike/Roguelike/build_test/test_skills_live_reload")
set_tests_properties([=[test_skills_live_reload]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/Roguelike/Roguelike/CMakeLists.txt;1324;add_test;/home/runner/work/Roguelike/Roguelike/CMakeLists.txt;0;")
add_test([=[test_map_debug]=] "/home/runner/work/Roguelike/Roguelike/build_test/test_map_debug")
set_tests_properties([=[test_map_debug]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/Roguelike/Roguelike/CMakeLists.txt;1334;add_test;/home/runner/work/Roguelike/Roguelike/CMakeLists.txt;0;")
add_test([=[test_skills_ordering_invariance]=] "/home/runner/work/Roguelike/Roguelike/build_test/test_skills_ordering_invariance")
set_tests_properties([=[test_skills_ordering_invariance]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/Roguelike/Roguelike/CMakeLists.txt;633;add_test;/home/runner/work/Roguelike/Roguelike/CMakeLists.txt;1341;rogue_add_test;/home/runner/work/Roguelike/Roguelike/CMakeLists.txt;0;")
add_test([=[test_skills_phase10_coeffs_loader]=] "/home/runner/work/Roguelike/Roguelike/build_test/test_skills_phase10_coeffs_loader")
set_tests_properties([=[test_skills_phase10_coeffs_loader]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/Roguelike/Roguelike/CMakeLists.txt;633;add_test;/home/runner/work/Roguelike/Roguelike/CMakeLists.txt;1348;rogue_add_test;/home/runner/work/Roguelike/Roguelike/CMakeLists.txt;0;")
add_test([=[test_effectspec_json_loader]=] "/home/runner/work/Roguelike/Roguelike/build_test/test_effectspec_json_loader")
set_tests_properties([=[test_effectspec_json_loader]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/Roguelike/Roguelike/CMakeLists.txt;633;add_test;/home/runner/work/Roguelike/Roguelike/CMakeLists.txt;1356;rogue_add_test;/home/runner/work/Roguelike/Roguelike/CMakeLists.txt;0;")
add_test([=[test_effectspec_spawn_projectile]=] "/home/runner/work/Roguelike/Roguelike/build_test/test_effectspec_spawn_projectile")
set_tests_properties([=[test_effectspec_spawn_projectile]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/Roguelike/Roguelike/CMakeLists.txt;633;add_test;/home/runner/work/Roguelike/Roguelike/CMakeLists.txt;1364;rogue_add_test;/home/runner/work/Roguelike/Roguelike/CMakeLists.txt;0;")
add_test([=[test_effectspec_timing_and_conditionals]=] "/home/runner/work/Roguelike/Roguelike/build_test/test_effectspec_timing_and_conditionals")
set_tests_properties([=[test_effectspec_timing_and_conditionals]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/Roguelike/Roguelike/CMakeLists.txt;633;add_test;/home/runner/work/Roguelike/Roguelike/CMakeLists.txt;1371;rogue_add_test;/home/runner/work/Roguelike/Roguelike/CMakeLists.txt;0;")
add_test([=[test_skills_phase10_3_validator]=] "/home/runner/work/Roguelike/Roguelike/build_test/test_skills_phase10_3_validator")
set_tests_properties([=[test_skills_phase10_3_validator]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/Roguelike/Roguelike/CMakeLists.txt;633;add_test;/home/runner/work/Roguelike/Roguelike/CMakeLists.txt;1381;rogue_add_test;/home/runner/work/Roguelike/Roguelike/CMakeLists.txt;0;")
add_test([=[test_skills_crossref_validation_ext]=] "/home/runner/work/Roguelike/Roguelike/build_test/test_skills_crossref_validation_ext")
set_tests_properties([=[test_skills_crossref_validation_ext]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/Roguelike/Roguelike/CMakeLists.txt;633;add_test;/home/runner/work/Roguelike/Roguelike/CMakeLists.txt;1389;rogue_add_test;/home/runner/work/Roguelike/Roguelike/CMakeLists.txt;0;")
add_test([=[test_audio_vfx_phase2_2_mixer_gain]=] "/home/runner/work/Roguelike/Roguelike/build_test/test_audio_vfx_phase2_2_mixer_gain")
set_tests_properties([=[test_audio_vfx_phase2_2_mixer_gain]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/Roguelike/Roguelike/CMakeLists.txt;633;add_test;/home/runner/work/Roguelike/Roguelike/CMakeLists.txt;1405;rogue_add_test;/home/runner/work/Roguelike/Roguelike/CMakeLists.txt;0;")
add_test([=[test_audio_vfx_phase2_3_mute]=] "/home/runner/work/Roguelike/Roguelike/build_test/test_audio_vfx_phase2_3_mute")
set_tests_properties([=[test_audio_vfx_phase2_3_mute]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/Roguelike/Roguelike/CMakeLists.txt;633;add_test;/home/runner/work/Roguelike/Roguelike/CMakeLists.txt;1409;rogue_add_test;/home/runner/work/Roguelike/Roguelike/CMakeLists.txt;0;")
add_test([=[test_audio_vfx_phase2_6_positional]=] "/home/runner/work/Roguelike/Roguelike/build_test/test_audio_vfx_phase2_6_positional")
set_tests_properties([=[test_audio_vfx_phase2_6_positional]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/Roguelike/Roguelike/CMakeLists.txt;633;add_test;/home/runner/work/Roguelike/Roguelike/CMakeLists.txt;1413;rogue_add_test;/home/runner/work/Roguelike/Roguelike/CMakeLists.txt;0;")
add_test([=[test_audio_vfx_phase2_1_registry_clear]=] "/home/runner/work/Roguelike/Roguelike/build_test/test_audio_vfx_phase2_1_registry_clear")
set_tests_properties([=[test_audio_vfx_phase2_1_registry_clear]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/Roguelike/Roguelike/CMakeLists.txt;633;add_test;/home/runner/work/Roguelike/Roguelike/CMakeLists.txt;1417;rogue_add_test;/home/runner/work/Roguelike/Roguelike/CMakeLists.txt;0;")
add_test([=[test_audio_vfx_phase3_1_vfx_foundations]=] "/home/runner/work/Roguelike/Roguelike/build_test/test_audio_vfx_phase3_1_vfx_foundations")
set_tests_properties([=[test_audio_vfx_phase3_1_vfx_foundations]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/Roguelike/Roguelike/CMakeLists.txt;633;add_test;/home/runner/work/Roguelike/Roguelike/CMakeLists.txt;1421;rogue_add_test;/home/runner/work/Roguelike/Roguelike/CMakeLists.txt;0;")
add_test([=[test_audio_vfx_phase3_2_particles_core]=] "/home/runner/work/Roguelike/Roguelike/build_test/test_audio_vfx_phase3_2_particles_core")
set_tests_properties([=[test_audio_vfx_phase3_2_particles_core]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/Roguelike/Roguelike/CMakeLists.txt;633;add_test;/home/runner/work/Roguelike/Roguelike/CMakeLists.txt;1425;rogue_add_test;/home/runner/work/Roguelike/Roguelike/CMakeLists.txt;0;")
add_test([=[test_audio_vfx_phase3_4_particle_layer_order]=] "/home/runner/work/Roguelike/Roguelike/build_test/test_audio_vfx_phase3_4_particle_layer_order")
set_tests_properties([=[test_audio_vfx_phase3_4_particle_layer_order]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/Roguelike/Roguelike/CMakeLists.txt;633;add_test;/home/runner/work/Roguelike/Roguelike/CMakeLists.txt;1429;rogue_add_test;/home/runner/work/Roguelike/Roguelike/CMakeLists.txt;0;")
add_test([=[test_audio_vfx_phase3_6_screen_vs_world]=] "/home/runner/work/Roguelike/Roguelike/build_test/test_audio_vfx_phase3_6_screen_vs_world")
set_tests_properties([=[test_audio_vfx_phase3_6_screen_vs_world]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/Roguelike/Roguelike/CMakeLists.txt;633;add_test;/home/runner/work/Roguelike/Roguelike/CMakeLists.txt;1433;rogue_add_test;/home/runner/work/Roguelike/Roguelike/CMakeLists.txt;0;")
add_test([=[test_audio_vfx_phase4_1_vfx_config_loader]=] "/home/runner/work/Roguelike/Roguelike/build_test/test_audio_vfx_phase4_1_vfx_config_loader")
set_tests_properties([=[test_audio_vfx_phase4_1_vfx_config_loader]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/Roguelike/Roguelike/CMakeLists.txt;633;add_test;/home/runner/work/Roguelike/Roguelike/CMakeLists.txt;1437;rogue_add_test;/home/runner/work/Roguelike/Roguelike/CMakeLists.txt;0;")
add_test([=[test_audio_vfx_phase4_2_hot_reload_and_validation]=] "/home/runner/work/Roguelike/Roguelike/build_test/test_audio_vfx_phase4_2_hot_reload_and_validation")
set_tests_properties([=[test_audio_vfx_phase4_2_hot_reload_and_validation]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/Roguelike/Roguelike/CMakeLists.txt;633;add_test;/home/runner/work/Roguelike/Roguelike/CMakeLists.txt;1441;rogue_add_test;/home/runner/work/Roguelike/Roguelike/CMakeLists.txt;0;")
add_test([=[test_audio_vfx_phase4_3_composition]=] "/home/runner/work/Roguelike/Roguelike/build_test/test_audio_vfx_phase4_3_composition")
set_tests_properties([=[test_audio_vfx_phase4_3_composition]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/Roguelike/Roguelike/CMakeLists.txt;633;add_test;/home/runner/work/Roguelike/Roguelike/CMakeLists.txt;1484;rogue_add_test;/home/runner/work/Roguelike/Roguelike/CMakeLists.txt;0;")
add_test([=[test_audio_vfx_phase4_4_parameter_overrides]=] "/home/runner/work/Roguelike/Roguelike/build_test/test_audio_vfx_phase4_4_parameter_overrides")
set_tests_properties([=[test_audio_vfx_phase4_4_parameter_overrides]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/Roguelike/Roguelike/CMakeLists.txt;633;add_test;/home/runner/work/Roguelike/Roguelike/CMakeLists.txt;1488;rogue_add_test;/home/runner/work/Roguelike/Roguelike/CMakeLists.txt;0;")
add_test([=[test_audio_vfx_phase4_5_random_distributions]=] "/home/runner/work/Roguelike/Roguelike/build_test/test_audio_vfx_phase4_5_random_distributions")
set_tests_properties([=[test_audio_vfx_phase4_5_random_distributions]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/Roguelike/Roguelike/CMakeLists.txt;633;add_test;/home/runner/work/Roguelike/Roguelike/CMakeLists.txt;1491;rogue_add_test;/home/runner/work/Roguelike/Roguelike/CMakeLists.txt;0;")
add_test([=[test_item_debug_api]=] "/home/runner/work/Roguelike/Roguelike/build_test/test_item_debug_api")
set_tests_properties([=[test_item_debug_api]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/Roguelike/Roguelike/CMakeLists.txt;633;add_test;/home/runner/work/Roguelike/Roguelike/CMakeLists.txt;1499;rogue_add_test;/home/runner/work/Roguelike/Roguelike/CMakeLists.txt;0;")
add_test([=[test_audio_vfx_phase5_1_mapping]=] "/home/runner/work/Roguelike/Roguelike/build_test/test_audio_vfx_phase5_1_mapping")
set_tests_properties([=[test_audio_vfx_phase5_1_mapping]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/Roguelike/Roguelike/CMakeLists.txt;633;add_test;/home/runner/work/Roguelike/Roguelike/CMakeLists.txt;1504;rogue_add_test;/home/runner/work/Roguelike/Roguelike/CMakeLists.txt;0;")
add_test([=[test_audio_vfx_phase5_2_damage_hook]=] "/home/runner/work/Roguelike/Roguelike/build_test/test_audio_vfx_phase5_2_damage_hook")
set_tests_properties([=[test_audio_vfx_phase5_2_damage_hook]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/Roguelike/Roguelike/CMakeLists.txt;633;add_test;/home/runner/work/Roguelike/Roguelike/CMakeLists.txt;1512;rogue_add_test;/home/runner/work/Roguelike/Roguelike/CMakeLists.txt;0;")
add_test([=[test_audio_vfx_phase5_3_skill_cues]=] "/home/runner/work/Roguelike/Roguelike/build_test/test_audio_vfx_phase5_3_skill_cues")
set_tests_properties([=[test_audio_vfx_phase5_3_skill_cues]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/Roguelike/Roguelike/CMakeLists.txt;633;add_test;/home/runner/work/Roguelike/Roguelike/CMakeLists.txt;1520;rogue_add_test;/home/runner/work/Roguelike/Roguelike/CMakeLists.txt;0;")
add_test([=[test_audio_vfx_phase5_4_buff_triggers]=] "/home/runner/work/Roguelike/Roguelike/build_test/test_audio_vfx_phase5_4_buff_triggers")
set_tests_properties([=[test_audio_vfx_phase5_4_buff_triggers]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/Roguelike/Roguelike/CMakeLists.txt;633;add_test;/home/runner/work/Roguelike/Roguelike/CMakeLists.txt;1528;rogue_add_test;/home/runner/work/Roguelike/Roguelike/CMakeLists.txt;0;")
add_test([=[test_audio_vfx_phase5_5_loot_drop]=] "/home/runner/work/Roguelike/Roguelike/build_test/test_audio_vfx_phase5_5_loot_drop")
set_tests_properties([=[test_audio_vfx_phase5_5_loot_drop]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/Roguelike/Roguelike/CMakeLists.txt;633;add_test;/home/runner/work/Roguelike/Roguelike/CMakeLists.txt;1536;rogue_add_test;/home/runner/work/Roguelike/Roguelike/CMakeLists.txt;0;")
add_test([=[test_audio_vfx_phase1_2]=] "/home/runner/work/Roguelike/Roguelike/build_test/test_audio_vfx_phase1_2")
set_tests_properties([=[test_audio_vfx_phase1_2]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/Roguelike/Roguelike/CMakeLists.txt;633;add_test;/home/runner/work/Roguelike/Roguelike/CMakeLists.txt;1597;rogue_add_test;/home/runner/work/Roguelike/Roguelike/CMakeLists.txt;0;")
add_test([=[test_audio_vfx_phase1_5_compaction]=] "/home/runner/work/Roguelike/Roguelike/build_test/test_audio_vfx_phase1_5_compaction")
set_tests_properties([=[test_audio_vfx_phase1_5_compaction]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/Roguelike/Roguelike/CMakeLists.txt;633;add_test;/home/runner/work/Roguelike/Roguelike/CMakeLists.txt;1598;rogue_add_test;/home/runner/work/Roguelike/Roguelike/CMakeLists.txt;0;")
subdirs("tests")
