function(rogue_set_project_warnings out_var)
    set(warnings)
    if(MSVC)
        list(APPEND warnings /W4 /permissive- /sdl)
    else()
        list(APPEND warnings -Wall -Wextra -Wpedantic -Wconversion -Wdouble-promotion -Wshadow -Wpointer-arith -Wformat=2 -Wimplicit-fallthrough)
    endif()
    set(${out_var} ${warnings} PARENT_SCOPE)
endfunction()
