function(rogue_set_project_warnings out_var)
    set(warnings)
    if(MSVC)
        list(APPEND warnings /W4 /permissive- /sdl)
        if(DEFINED ROGUE_WARNINGS_AS_ERRORS AND ROGUE_WARNINGS_AS_ERRORS)
            list(APPEND warnings /WX)
        endif()
    else()
        list(APPEND warnings -Wall -Wextra -Wpedantic -Wconversion -Wdouble-promotion -Wshadow -Wpointer-arith -Wformat=2 -Wimplicit-fallthrough)
        if(DEFINED ROGUE_WARNINGS_AS_ERRORS AND ROGUE_WARNINGS_AS_ERRORS)
            list(APPEND warnings -Werror)
        endif()
    endif()
    set(${out_var} ${warnings} PARENT_SCOPE)
endfunction()
