name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-test-windows:
    name: Build & Test (windows-latest)
    runs-on: windows-latest
    env:
      BUILD_TYPE: Debug
      ROGUE_ENABLE_SDL: OFF
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install clang-format (Windows)
        shell: pwsh
        run: |
          choco install -y llvm || echo "llvm already installed"
          if (Get-Command clang-format -ErrorAction SilentlyContinue) { clang-format --version }

      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v1

      - name: Configure (Windows, SDL OFF)
        run: >-
          cmake -S . -B build
          -DROGUE_ENABLE_SDL=${{ env.ROGUE_ENABLE_SDL }}
          -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}

      - name: Build (Windows)
        run: cmake --build build --config ${{ env.BUILD_TYPE }} -- -j 8

      - name: Format Check
        run: |
          set -e
          cmake --build build --target format-check || (
            echo "Format check failed. Run: cmake --build build --target format";
            exit 1
          )

      - name: Run Tests
        run: ctest --test-dir build -C ${{ env.BUILD_TYPE }} --output-on-failure

      - name: clang-tidy Summary (best-effort)
        if: always()
        run: |
          echo "If clang-tidy is configured it ran during the build (via target property)."
