name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-test-windows:
    name: Build & Test (windows-latest)
    runs-on: windows-latest
    env:
      BUILD_TYPE: Debug
      ROGUE_ENABLE_SDL: ON
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install clang-format (Windows)
        shell: pwsh
        run: |
          choco install -y llvm || echo "llvm already installed"
          if (Get-Command clang-format -ErrorAction SilentlyContinue) { clang-format --version }

      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v1

      - name: Configure (Windows, SDL ON)
        run: >-
          cmake -S . -B build -DROGUE_ENABLE_SDL=${{ env.ROGUE_ENABLE_SDL }} -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}

      - name: Build (Windows, -j12)
        run: cmake --build build --config ${{ env.BUILD_TYPE }} --parallel 12

      - name: Format Check
        run: |
          set -e
          cmake --build build --target format-check || (
            echo "Format check failed. Run: cmake --build build --target format";
            exit 1
          )

      - name: Run Tests (-j12)
        run: ctest --test-dir build -C ${{ env.BUILD_TYPE }} -j12 --output-on-failure

  docs:
    name: Build Docs (windows-latest)
    runs-on: windows-latest
    needs: build-test-windows
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v1

      - name: Install Doxygen and Graphviz
        shell: pwsh
        run: |
          choco install -y doxygen.portable graphviz || echo "doxygen/graphviz already installed"
          doxygen -v

      - name: Configure (SDL ON for parity)
        run: >-
          cmake -S . -B build -DROGUE_ENABLE_SDL=ON -DCMAKE_BUILD_TYPE=Debug

      - name: Build core (optional, ensures headers/configs)
        run: cmake --build build --config Debug --parallel 12

      - name: Generate Doxygen docs
        run: cmake --build build --target docs --config Debug

      - name: Upload HTML docs artifact
        uses: actions/upload-artifact@v4
        with:
          name: docs-html
          path: build/docs/html

      - name: clang-tidy Summary (best-effort)
        if: always()
        run: |
          echo "If clang-tidy is configured it ran during the build (via target property)."
